# purely for running locally - for now
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    env_file: 
      - .env.development
volumes:
  db:
    driver: local
